controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
index:
   path: /andrana
   controller: App\Controller\FirstController::test

